prefix : <http://stardog.com/sbdashboard#>
prefix br: <http://stardog.com/sbdashboard/branches/>
prefix test: <http://stardog.com/sbdashboard/tests/>

SELECT ?testIri ?build ?commit ?clients ?actual ?date
FROM stardog:context:local
{     
  #pragma push.filters aggressive
#  BIND(test:bsbm100m_explore_barq AS ?testIri)
  BIND(br:develop AS ?branch)
  BIND(false AS ?cluster) 
  FILTER(?date >= xsd:date(NOW() - "P?num_daysD"^^xsd:duration))
  ?group a :RunGroup ;
        :forBranch ?branch ;
        :buildNum ?build ;
        :buildHash ?commit ;
        :forStarbenchBranch br:SB_master ;
        :hasRun ?run .
  ?run :forTest ?testIri ;
      :date ?date ;
      :cluster ?cluster;
      :data ?data .
  
  ?data :clients ?clients ;
        :actualValue ?actual
}
order by desc(?build) ?clients
